language:  python
python:
  - "2.7"
install:
  - CFLAGS="-O0" pip install -r requirements-tests.txt
  - pip install coveralls
script:
  - cp config/settings.sample.ini config/settings.ini
  - sed -i 's/DEBUG\s*=\s*0/DEBUG = 1/' config/settings.ini
  - ./runtests.py
after_success:
  - coveralls
